# Generated by Django 3.1.2 on 2021-04-19 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='note',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notebooks.notebook', verbose_name='notebook'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
