# Generated by Django 3.1.2 on 2021-04-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0003_note_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='cover',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='cover'),
        ),
    ]
