# Generated by Django 3.1.2 on 2021-04-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0004_auto_20210419_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='title'),
        ),
    ]
