# Generated by Django 3.1.2 on 2021-04-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0005_auto_20210419_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='data',
            field=models.CharField(default='', max_length=200, verbose_name='data'),
        ),
    ]
